### PR TITLE
edits that you contacted me to make

### PR DESCRIPTION
**Pull request by voltt10**
for all of the role names, just change them. it's not only these files, but the others that have the .some(role... etc.)

### CODE REVIEW

**Comment by iRadd** [comment]
thanks

**Comment by iRadd** [comment]
should i make the ids a config thing?

**Comment by voltt10** [comment]
whatever you choose

**Comment by voltt10** [comment]
you forgot to add the ids

**Comment by iRadd** [comment]
ya ill do it soon

**Comment by iRadd** [comment]
verified id - 855081624956960788

**Pull request merged**
